ERAS = [
    {"name": "Mega Evolution"},
    {"name": "Scarlet & Violet"},
    {"name": "Sword & Shield"},
    {"name": "Sun & Moon"},
    {"name": "XY"},
    {"name": "Black & White"},
    {"name": "Black & White Promos"},
    {"name": "Call of Legends"},
    {"name": "HeartGold SoulSilver"},
    {"name": "Platinum"},
    {"name": "Nintendo Promos"},
    {"name": "Diamond & Pearl"},
    {"name": "EX Ruby & Sapphire"},
    {"name": "e-Card"},
    {"name": "Legendary Collection"},
    {"name": "Neo Genesis"},
    {"name": "Topps Chrome"},
    {"name": "Gym Heroes"},
    {"name": "Base Set"},
]

CARD_RARITY = [
        {"code": "C", "name": "Common"},
        {"code": "U", "name": "Uncommon"},
        {"code": "R", "name": "Rare"},
        {"code": "H", "name": "Holo Rare"},
        {"code": "RH", "name": "Reverse Holo"},
        {"code": "IR", "name": "Illustration Rare"},
        {"code": "RR", "name": "Double Rare"},
        {"code": "SIR", "name": "Special Illustration Rare"},
        {"code": "UR", "name": "Ultra Rare"},
        {"code": "HR", "name": "Hyper Rare"}
    ]

CARDS = [
    {"set_id": 19, "card_number": "001", "name": "Tangela", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "002", "name": "Tangrowth", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "003", "name": "Pansage", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "004", "name": "Simisage", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "005", "name": "Deerling", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "006", "name": "Sawsbuck", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "007", "name": "Skiddo", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "008", "name": "Gogoat", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "009", "name": "Vulpix", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "010", "name": "Ninetales", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "011", "name": "Growlithe", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "012", "name": "Arcanine", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "013", "name": "Moltres ex", "rarity_id": 3, "image_url": None},
    {"set_id": 19, "card_number": "014", "name": "Cyndaquil", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "015", "name": "Quilava", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "016", "name": "Typhlosion", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "017", "name": "Houndour", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "018", "name": "Houndoom", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "019", "name": "Torchic", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "020", "name": "Combusken", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "021", "name": "Blaziken", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "022", "name": "Pansear", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "023", "name": "Simisear", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "024", "name": "Fennekin", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "025", "name": "Braixen", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "026", "name": "Delphox", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "027", "name": "Litleo", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "028", "name": "Pyroar", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "029", "name": "Seel", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "030", "name": "Dewgong", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "031", "name": "Lapras", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "032", "name": "Articuno ex", "rarity_id": 3, "image_url": None},
    {"set_id": 19, "card_number": "033", "name": "Marill", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "034", "name": "Azumarill", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "035", "name": "Panpour", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "036", "name": "Simipour", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "037", "name": "Froakie", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "038", "name": "Frogadier", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "039", "name": "Greninja", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "040", "name": "Clauncher", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "041", "name": "Clawitzer", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "042", "name": "Pikachu", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "043", "name": "Raichu", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "044", "name": "Voltorb", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "045", "name": "Electrode", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "046", "name": "Zapdos ex", "rarity_id": 3, "image_url": None},
    {"set_id": 19, "card_number": "047", "name": "Mareep", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "048", "name": "Flaaffy", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "049", "name": "Ampharos", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "050", "name": "Helioptile", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "051", "name": "Heliolisk", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "052", "name": "Clefairy", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "053", "name": "Clefable", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "054", "name": "Jigglypuff", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "055", "name": "Wigglytuff", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "056", "name": "Mr. Mime", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "057", "name": "Mewtwo ex", "rarity_id": 3, "image_url": None},
    {"set_id": 19, "card_number": "058", "name": "Mew ex", "rarity_id": 3, "image_url": None},
    {"set_id": 19, "card_number": "059", "name": "Espurr", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "060", "name": "Meowstic", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "061", "name": "Spritzee", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "062", "name": "Aromatisse", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "063", "name": "Sylveon ex", "rarity_id": 3, "image_url": None},
    {"set_id": 19, "card_number": "064", "name": "Xerneas", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "065", "name": "Diglett", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "066", "name": "Dugtrio", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "067", "name": "Mankey", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "068", "name": "Primeape", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "069", "name": "Annihilape", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "070", "name": "Cubone", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "071", "name": "Marowak ex", "rarity_id": 3, "image_url": None},
    {"set_id": 19, "card_number": "072", "name": "Hitmonlee", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "073", "name": "Hitmonchan", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "074", "name": "Phanpy", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "075", "name": "Donphan", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "076", "name": "Meowth", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "077", "name": "Persian", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "078", "name": "Lickitung", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "079", "name": "Lickilicky", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "080", "name": "Eevee", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "081", "name": "Snorlax", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "082", "name": "Slakoth", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "083", "name": "Vigoroth", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "084", "name": "Slaking", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "085", "name": "Skitty", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "086", "name": "Delcatty", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "087", "name": "Bunnelby", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "088", "name": "Diggersby", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "089", "name": "Fletchling", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "090", "name": "Yveltal", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "091", "name": "Noibat", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "092", "name": "Noivern", "rarity_id": 1, "image_url": None},
    {"set_id": 19, "card_number": "093", "name": "Zygarde ex", "rarity_id": 3, "image_url": None},
    {"set_id": 19, "card_number": "094", "name": "Diancie ex", "rarity_id": 3, "image_url": None},
    {"set_id": 19, "card_number": "095",  "name": "Ludicolo", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "096",  "name": "Nymble", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "097",  "name": "Dewgong", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "098",  "name": "Piplup", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "099",  "name": "Yamper", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "100",  "name": "Zacian", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "101",  "name": "Flygon", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "102",  "name": "Paldean Wooper", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "103",  "name": "Toxtricity", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "104",  "name": "Togedemaru", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "105",  "name": "Wigglytuff", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "106",  "name": "Meowth", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "107",  "name": "Ambipom", "rarity_id": 6, "image_url": None},
    {"set_id": 19, "card_number": "108",  "name": "Mega Heracross ex", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "109",  "name": "Mega Charizard X ex", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "110",  "name": "Orocorio", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "111",  "name": "Rotom ex", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "112",  "name": "Mismagius", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "113",  "name": "Mega Sharpedo ex", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "114",  "name": "Empoleon ex", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "115",  "name": "Mega Lopunny ex", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "116",  "name": "Battle Cage", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "117",  "name": "Blowtorch", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "118",  "name": "Dawn", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "119",  "name": "Firebreather", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "120",  "name": "Grimsley's Move", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "121",  "name": "Punk Helmet", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "122",  "name": "Sacred Charm", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "123",  "name": "Switch", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "124",  "name": "Ignition Energy", "rarity_id": 7, "image_url": None},
    {"set_id": 19, "card_number": "125",  "name": "Mega Charizard X", "rarity_id": 8, "image_url": None},
    {"set_id": 19, "card_number": "126",  "name": "Rotom ex", "rarity_id": 8, "image_url": None},
    {"set_id": 19, "card_number": "127",  "name": "Mega Sharpedo ex", "rarity_id": 8, "image_url": None},
    {"set_id": 19, "card_number": "128",  "name": "Mega Lopunny ex", "rarity_id": 8, "image_url": None},
    {"set_id": 19, "card_number": "129",  "name": "Dawn", "rarity_id": 8, "image_url": None},
    {"set_id": 19, "card_number": "130",  "name": "Mega Charizard X ex", "rarity_id": 10, "image_url": None}
]
